services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "tiny10"  
     RAM_SIZE: "2G"
    CPU_CORES: "2"
    DISK_SIZE: "30G"
          KVM: "N"
      
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
